// Generated by CoffeeScript 1.6.2
(function() {
  var file, fs, json, kidSkillsInfo, listifyQuestionType, mentorSkillsInfo, profile, profiles, quantifySkillList, _;

  fs = require('fs');

  _ = require('underscore');

  listifyQuestionType = function(list, id, name, conditionCheck) {
    var item, question, _i, _len, _results;

    _results = [];
    for (_i = 0, _len = list.length; _i < _len; _i++) {
      item = list[_i];
      question = null;
      if (conditionCheck(item)) {
        question = _.find(item.answers, function(item) {
          return item.question_id === id;
        });
      }
      if ((question != null) && (question.answer != null)) {
        question.answer = _.map(question.answer.split(','), function(str) {
          return str.trim().toLowerCase();
        });
      }
      _results.push(item[name] = question);
    }
    return _results;
  };

  quantifySkillList = function(profiles, questionName) {
    var profile, skillCounts, skillList, _i, _len;

    skillList = [];
    for (_i = 0, _len = profiles.length; _i < _len; _i++) {
      profile = profiles[_i];
      if (profile[questionName] != null) {
        skillList.push.apply(skillList, profile[questionName].answer);
      }
    }
    skillCounts = _.reduce(skillList.sort(), function(counts, skill) {
      if (counts[skill] == null) {
        counts[skill] = 0;
      }
      counts[skill]++;
      return counts;
    }, {});
    skillCounts = _.chain(skillCounts).pairs().sortBy(function(skillCount) {
      return -skillCount[1];
    }).value();
    return {
      skillList: skillList,
      skillCounts: skillCounts
    };
  };

  file = fs.readFileSync('./Profiles.json', 'utf8');

  json = JSON.parse(file);

  profiles = (function() {
    var _i, _len, _ref, _results;

    _ref = json.results;
    _results = [];
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      profile = _ref[_i];
      _results.push({
        name: profile.name,
        bio: profile.bio,
        answers: profile.answers,
        mentor: profile.mentor
      });
    }
    return _results;
  })();

  listifyQuestionType(profiles, 4402172, 'mentorQuestion', function(profile) {
    return profile.mentor;
  });

  listifyQuestionType(profiles, 4402182, 'parentQuestion', function() {
    return true;
  });

  mentorSkillsInfo = quantifySkillList(profiles, 'mentorQuestion');

  kidSkillsInfo = quantifySkillList(profiles, 'parentQuestion');

  console.dir(mentorSkillsInfo);

  console.dir(kidSkillsInfo);

}).call(this);
