// Generated by CoffeeScript 1.6.2
(function() {
  angular.module("mongolab", ["ngResource"]).factory("Signup", function($resource) {
    var Signup, options;

    options = {
      apiKey: "bWK-cL1WKkJF6yyunAhSjhszvkkTTOlM",
      update: {
        method: "PUT"
      }
    };
    Signup = $resource("https://api.mongolab.com/api/1/databases/coderdojosignup/collections/signups/:id", options);
    Signup.prototype.update = function(cb) {
      return Signup.update({
        id: this._id.$oid
      }, angular.extend({}, this, {
        _id: undefined
      }), cb);
    };
    return Signup.prototype.destroy = function(cb) {
      return Signup.remove({
        id: this._id.$oid
      }, cb);
    };
  });

}).call(this);
