// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = {
    mentorSkills: ['Arduino / Raspberry Pi / Hardware hacking', 'CSS', 'HTML5', 'JavaScript', 'Node.js', 'Scratch', 'Python', 'PERL', 'Ruby', 'PHP', 'Java', 'Scala', 'C#', 'F#', 'Robotics'],
    volunteerOffers: ['Mentoring kids on technology', 'Leading a 4-week exploration on a topic', 'Donating or reimaging computers', 'Reaching out to local schools to tell them about CoderDojo Ponce Springs', 'Supporting events as a volunteer'],
    availability: ['Sat January 25, 2 - 5 PM'],
    tshirtSizes: ['Small', 'Medium', 'Large', 'X-Large', 'XX-Large']
  };

}).call(this);
