// Generated by CoffeeScript 1.6.3
(function() {
  var clientConfiguration, createServer, express, serverConfiguration, sg;

  express = require('express');

  sg = require('sendgrid-nodejs');

  clientConfiguration = require('./clientConfiguration');

  serverConfiguration = require('./serverConfiguration');

  createServer = function() {
    var app;
    app = express();
    app.configure(function() {
      var port;
      app.use('/app', express["static"]('../../client/app'));
      app.use(express.bodyParser());
      app.use(app.router);
      port = process.env.PORT || 8081;
      return app.listen(port);
    });
    app.get('/clientConfiguration', function(req, res) {
      return res.send(clientConfiguration);
    });
    app.post('/submit', function(req, res) {
      var from, header, headerHtml, headerText, html, htmlToHost, mail, mailForVolunteer, sender, signup, text;
      if (req.body == null) {
        return;
      }
      signup = req.body;
      html = signup.html;
      delete signup.html;
      signup = JSON.stringify(signup, null, 4);
      header = serverConfiguration.emailToHostHeaderFormat(req);
      text = header + signup;
      htmlToHost = header + html;
      from = serverConfiguration.emailFrom;
      mail = new sg.Email({
        to: serverConfiguration.emailTo,
        from: req.body.email,
        subject: serverConfiguration.emailToHostSubjectFormat(req),
        text: text,
        html: htmlToHost
      });
      headerText = serverConfiguration.emailToVolunteerTextFormat(req);
      headerHtml = serverConfiguration.emailToVolunteerHtmlFormat(req);
      text = headerText + signup;
      html = headerHtml + html;
      mailForVolunteer = new sg.Email({
        to: req.body.email,
        from: from,
        subject: serverConfiguration.emailToVolunteerSubject,
        text: text,
        html: html,
        files: {
          'CoderDojoPonceSprings-BackgroundCheckAuthorization.pdf': __dirname + '/../../client/app/content/CoderDojoPonceSprings-BackgroundCheckAuthorization.pdf'
        }
      });
      sender = new sg.SendGrid('azure_087394ee528ccb83063ec69cc1b4f2cf@azure.com', 'jpzmaq95');
      sender.send(mail, function(success, err) {
        if (success) {
          return console.log('Email sent');
        } else {
          return console.log(err);
        }
      });
      sender.send(mailForVolunteer, function(success, err) {
        if (success) {
          return console.log('Email sent to volunteer');
        } else {
          return console.log(err);
        }
      });
      return res.send({
        status: 200,
        message: 'Success'
      });
    });
    return app;
  };

  module.exports = createServer;

}).call(this);
